In [2]:
import numpy as np


In [8]:
matrix_a = np.arange(9).reshape((3,3))
print(matrix_a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
print(np.max(matrix_a)) #Max overall
print(np.max(matrix_a,axis=0)) #max in raw
print(np.max(matrix_a,axis=1)) #max in column


8
[6 7 8]
[2 5 8]


In [15]:
#find location
print(np.where(matrix_a == np.max(matrix_a))) #Max overall
print(np.where(matrix_a == np.max(matrix_a,axis=0))) # max in raw
print(np.where(matrix_a == np.max(matrix_a,axis=1))) #max in column



(array([2], dtype=int64), array([2], dtype=int64))
(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))
(array([2], dtype=int64), array([2], dtype=int64))
